### PR TITLE
Add continuous integration via travis and appveyor

### PR DESCRIPTION
**Pull request by jchodera**
Addresses #4

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like the rest are real errors, @gregoryross.

One of them is just an issue where you force the `CUDA` platform. If this is a slow test, you might want to skip it with `@attr('slow')`. If not, you should probably let OpenMM pick the fastest platform for you.

I'll let you finish this up, @gregoryross! The tests are running.

**Comment by jchodera** [comment]
@gregoryross : Just a reminder that this PR is complete, but the tests found there were issues with the code due to missing imports. I'm done with it, so you should pick it up and fix the issues at your convenience.

**Comment by bas-rustenburg** [comment]
@gregoryross , let me know if you're interested in monitoring test coverage from your travis builds. This might be a good moment to add it in. I've found the codecov reports handy https://github.com/choderalab/protons/pull/89#issuecomment-305305496.

**Comment by jchodera** [comment]
Woohoo! Looks like test pass!

**Comment by gregoryross** [comment]
@bas-rustenburg, adding a code coverage report sounds a like good idea. Grab me when you're free?

**Comment by bas-rustenburg** [comment]
Cool, might end up being tomorrow. We can do this in a separate PR if that is easier.

**Comment by gregoryross** [comment]
@bas-rustenburg, as you, it'll probably be easier to save the codevcov reports for another PR.

**Pull request merged**
